# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.3
- 1.7.3
services:
  - docker
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/intelsdi-x/snap-plugin-publisher-cassandra
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=medium
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Ufa1xADxI24ANWRmtoRx7Z0e5ijYhwDHLuCyrTEy5KLlMsIvRzG+4+zLDk061M9dK0bhsfbqwGA2juT7T5ZMv4DbURAr5j9hvWqJgpJ9aNNcC0YMUSbc40QyRtRtcEWV/Zsgk+NOhC/ysdC43L6p8pZN4xaC3Ez+yDk5+ZhRMk713nZZu6mvl+F7jUz8iHsK1r7zGGoQzK3qCug6FXFHO+C56nFbSYKj/21H9jqgqPyw0l3MSyURjT8Q0C0Zw3u3T2yQxpGf9S7MUPGkLQQzUXLN/SBlDuHfi/9HiS9zFGI+i2sAQstYmSorHjI3VqmuzEpPNx8jiSMHBcEvPeRqBvJKxlQo56dmsvsheUL139Py8d7i6CUmMCLwMlZfbPX8FvtGvBpk+ieb7kOfikDUxYsi5ML9MXV7x+eYfZPB9UWRecHPW3P0OEFLFq3OSqRmmv1uUHD2TbbWVqpUT5AvhAXjnhCm3HRahA2AHfmSEZSBdATUgGfQ2mPKQbASitAxevbpahX7ovms7dIGEYhrP7xJvPHO9i9ASHSSyNkc/jLQeNK2sXYm9VyvPJcW+DBkzY3cPzq273uFASYTbbSZWTkLOD5tS60i8PjqgHXOKFs2Qc4crAvlBYRKYTz+mQfjJ8uIEEOqIQEoUpy/5SpFrt65vG7sBzWU6qMEUo3EooY=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: nanliu/snap-plugin-publisher-cassandra
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Ufa1xADxI24ANWRmtoRx7Z0e5ijYhwDHLuCyrTEy5KLlMsIvRzG+4+zLDk061M9dK0bhsfbqwGA2juT7T5ZMv4DbURAr5j9hvWqJgpJ9aNNcC0YMUSbc40QyRtRtcEWV/Zsgk+NOhC/ysdC43L6p8pZN4xaC3Ez+yDk5+ZhRMk713nZZu6mvl+F7jUz8iHsK1r7zGGoQzK3qCug6FXFHO+C56nFbSYKj/21H9jqgqPyw0l3MSyURjT8Q0C0Zw3u3T2yQxpGf9S7MUPGkLQQzUXLN/SBlDuHfi/9HiS9zFGI+i2sAQstYmSorHjI3VqmuzEpPNx8jiSMHBcEvPeRqBvJKxlQo56dmsvsheUL139Py8d7i6CUmMCLwMlZfbPX8FvtGvBpk+ieb7kOfikDUxYsi5ML9MXV7x+eYfZPB9UWRecHPW3P0OEFLFq3OSqRmmv1uUHD2TbbWVqpUT5AvhAXjnhCm3HRahA2AHfmSEZSBdATUgGfQ2mPKQbASitAxevbpahX7ovms7dIGEYhrP7xJvPHO9i9ASHSSyNkc/jLQeNK2sXYm9VyvPJcW+DBkzY3cPzq273uFASYTbbSZWTkLOD5tS60i8PjqgHXOKFs2Qc4crAvlBYRKYTz+mQfjJ8uIEEOqIQEoUpy/5SpFrt65vG7sBzWU6qMEUo3EooY=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: nanliu/snap-plugin-publisher-cassandra
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: releases
  api_key:
    secure: seEP9cKGbJ5F1Dpfso764IbZ3LSBc+aZ9PnL8bvlKsrEM7YLMoilRakBkeMEOYgA7H5HG5MpYC95EzFSfCAKg2zpdlNqyG9mV9+f2draltWb6wVEFo8+21h+IEGHP+dxoTBPbrploX2hyEQ9y4PD2IhJ5qumrADezSxT/YuIdMTEaTy8UlK92bLJLJhyBgN7MGS+vh9pJkftD+rDSi8DYoQqJt/T+4joCh7rRrSoHPsJt1EMI4GLyn14zI5NFr/Ip+YkXh80Ibg0bB1uKZ6+vQpINx/71GLmngBZbdkM0poH4l0cdGaifC61OEx14iNbgXCBMGmgqH5Dgxkx1XvJtNieScplTleYjXXqdXztvjYqHqX6xiEhlpER1bU/0Y/D52Ni8s7CzU0L3MAf0zP3VNKFQV5E58i0o7xbuUPHEyCizd+3c0RBFGU1sMKnGMtFIIWelsY2BqCLxhRt0XfkceQg70ZCHptPvrpVgLiMMy7QZON/+SEo4z6LDTJRXNjPhlEl7A4fKWPezxIhxKlhSCeVB8S54JGztz7emfz6ATUbHLIzNdaqdPbblCkQ+ckR8et6uuH0ILD1im83jvklpYqzBPZVYi+WxyD6Xrir80+nN8iuP1P0/0IuW1qc7KmnPoc+UBQB78IT+xYC4JjyAECBr8OgoWSBKq4y7OeNVSU=
  file:
    - release/snap-plugin-publisher-cassandra_linux_x86_64
  skip_cleanup: true
  on:
    repo: nanliu/snap-plugin-publisher-cassandra
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
